### ISSUE TITLE
Internal Exception: io.netty.handler.codec.DecoderException: Failed to decode packet 'clientbound/minecraft:level_chunk_with_light'

### ISSUE THREAD

**Issue by Ivanoshechka** [ILikeFood971/RegSyncFix#1]
I'm trying combine [Legacy4J](https://modrinth.com/mod/legacy4j) and option to play without mod.
 But sometimes there a huge chance to not connect to the server or being kicked even installed regsync on server and client.
 
![image](https://github.com/user-attachments/assets/5e7e818b-39f6-4766-8f85-a9c14c1c777a)

Maybe some mod on client is not allowing to connect when Legacy4J and RegSync on server installed. I don't know.

There the log: https://mclo.gs/N1IvdS8

There are server mods: 
![image](https://github.com/user-attachments/assets/9a8a85b7-83fa-44c3-9cde-496d7d3033d6)

**Comment by ILikeFood971** [comment]
As stated in RegSyncFix’s description, this will not allow mods to work on only one side that need both client and sever installed. Since Legacy4J is needed on the client this mod simply forces the client to try to join anyways but as the other mod sends its own custom packets you are not going to be able to play even with this mod unless you add the Legacy4J mod to your client.
